### ISSUE TITLE
IndexError: index <N> is out of bounds for axis 0 with size <N>

### ISSUE THREAD

**Issue by antonAtananasov** [mikefromlig/dollarN#2]
`File "dollarN.py", line 181, in optimal_cos_distance
    a += v1[i]*v2[i] + v1[i+1]*v2[i+1]
IndexError: index 192 is out of bounds for axis 0 with size 192`

Gives errors on the gestures `rectangle, caret, v, delete, star, pigtail` from the original $1 website:

line 180 in dollarN.py should be:
```
        if i+1 < len(v1) and i+1 < len(v2):
            a += v1[i]*v2[i] + v1[i+1]*v2[i+1]
            b += v1[i]*v2[i+1] - v1[i+1]*v2[i]
```

**Comment by mikefromlig** [comment]
Thanks @antonAtananasov for your feedback.
I updated line 180.
